### PR TITLE
don't use the api for strict version

### LINKED ISSUE #14: rate limit exceeded
with the last version, we sometime get this error:

~~~
Configured range: v0.6.29
Error: API rate limit exceeded for 65.108.86.252. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
~~~

my guess is that the action is requesting the available earthly versions (even though we specified a fixed version) and, as we are using it quite heavily, may do it too often.

As the error message suggest, a possible fix may be to authenticate when requesting github API, but I don't see anyway to pass a github token at this time.

### PR DESCRIPTION
**Pull request by glehmann**
fixes #14

### CODE REVIEW

**Comment by glehmann** [comment]
could someone give at look at these changes? That's a quite small one :-)

Thanks!

**Comment by glehmann** [comment]
could someone give a look at this change? That's just a small one, I promise :)

**Comment by glehmann** [comment]
@alexcb maybe?

**Review by alexcb — APPROVED** [review]
awesome work! apologies for not seeing this sooner.

**Comment by alexcb** [comment]
published under https://github.com/earthly/actions-setup/releases/tag/v1.0.4

**Comment by glehmann** [comment]
thanks!

**Pull request merged**
